# Generated by Django 5.1.1 on 2025-03-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='logout_car',
        ),
    ]
