# Generated by Django 5.1.1 on 2025-03-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_profile_logout_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logout_car',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
